var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/services/cultural-center/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f2a16d2._.js")
R.c("server/chunks/ssr/275cd_next_dist_c1c4d647._.js")
R.c("server/chunks/ssr/_aab70aea._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e8761408._.js")
R.c("server/chunks/ssr/[root-of-the-server]__025b4968._.js")
R.c("server/chunks/ssr/275cd_next_dist_3fb4b866._.js")
R.c("server/chunks/ssr/275cd_next_dist_client_components_builtin_global-error_832d590f.js")
R.c("server/chunks/ssr/[root-of-the-server]__0d1b06ef._.js")
R.c("server/chunks/ssr/_9ce30220._.js")
R.c("server/chunks/ssr/275cd_next_dist_client_components_44061dcf._.js")
R.c("server/chunks/ssr/275cd_next_dist_client_components_builtin_forbidden_83c1f1ca.js")
R.c("server/chunks/ssr/275cd_next_dist_client_components_builtin_unauthorized_9d117012.js")
R.c("server/chunks/ssr/_next-internal_server_app_services_cultural-center_page_actions_730b6484.js")
R.m(26949)
module.exports=R.m(26949).exports
