var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5ce8e09b._.js")
R.c("server/chunks/ssr/275cd_next_dist_c1c4d647._.js")
R.c("server/chunks/ssr/275cd_next_dist_esm_build_templates_app-page_367e1a55.js")
R.c("server/chunks/ssr/[root-of-the-server]__88ac17a5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__025b4968._.js")
R.c("server/chunks/ssr/275cd_next_dist_3fb4b866._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0d1b06ef._.js")
R.c("server/chunks/ssr/_9ce30220._.js")
R.c("server/chunks/ssr/275cd_next_dist_client_components_44061dcf._.js")
R.c("server/chunks/ssr/275cd_next_dist_client_components_builtin_forbidden_83c1f1ca.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_554ec2bf.js")
R.m(99184)
module.exports=R.m(99184).exports
